spring.application.name=f1
server.port=8080

# Base de datos MySQL
db.url=jdbc:mysql://54.156.150.241:3306/f1
db.usuario=consulta_f1
db.contrasena=Consulta123!

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.palomafp.f1=DEBUG

