spring.application.name=f1
server.port=8080

# Base de datos MySQL
db.url=jdbc:mysql://localhost:3306/f1
db.usuario=admin_f1
db.contrasena=Admin123!

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.palomafp.f1=DEBUG

